pipeline {
    agent {
        docker {
            image 'node' 
            args '-p 5000:5000' 
        }
    }
    dir("Backend") {
       sh "pwd"
        stages {
        stage('build') {
            steps {
                sh 'ls'
                sh 'npm install'
            }
        
        }
        
        stage('Test') {
            steps { 
              sh 'echo start test'
              sh 'ls'
              sh 'npm run test'
            }
            // post {
            //     always {
            //         junit 'test-reports/results.xml'
            //     }
            // }
        }
    }
    }
   
}