pipeline {
    agent {
        docker {
            image 'node' 
            args '-p 5000:5000' 
        }
    }
    dir("Backend") {
       sh "pwd"
    }
    stages {
        stage('build') {
                dir("Backend") {
                    steps {
                        sh 'pwd'
                        sh 'echo start build'
                        sh 'ls'
                        sh 'npm install'
                    }
             }
        
        }
        
        stage('Test') {
            dir("Backend") {
                 steps {
                     sh 'cd Backend'  
                     sh 'echo start test'
                     sh 'ls'
                    sh 'npm run test'
                 }
            }
            // post {
            //     always {
            //         junit 'test-reports/results.xml'
            //     }
            // }
        }
    }
}